# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
paginate:            5
paginate_path:      "/pagina/:num/"
timezone:            your timezone # eg. Asia/Kathmandu
locale:              your locale language # eg. en_us
name:				         test
title:               site title
tagline:             'tagline'
description:         'description'
url:                 site url
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"

# Authors
authors:
  felipeorlando:
    name: Felipe Orlando
    description: Lorem ipsum dolor sit amet
    slug: felipeorlando
    avatar: path/to/file.jpg
    facebook: ''
    github:   ''
    linkedin: ''
    twitter:  ''
  evansantos:
    name: Evan Cavalcante Santos
    description: Lorem ipsum dolor sit amet
    slug: evansantos
    avatar: path/to/file.jpg
    facebook: ''
    github:   ''
    linkedin: ''
    twitter:  ''
  loremipsum:
    name: Lorem Ipsum
    description: Dolor sit amet
    slug: dolorsit
    avatar: path/to/file.jpg
    facebook: ''
    github:   ''
    linkedin: ''
    twitter:  ''
